---
title: "lookup Rmarkdown"
output: html_document
---

```{r, warning = FALSE, message = FALSE}
library(tidyverse)

raw_data <- read_csv("final_project_app/data.csv") %>%
  select(-QKEY, -INTERVIEW_START_W56, -INTERVIEW_END_W56, -DEVICE_TYPE_W56, -SAMPLE_W56, -FORM_W56, -WHYDATE10YRHARDOE_M1_W56, -WHYDATE10YRHARDOE_M2_W56, -WHYDATE10YRHARDOE_M3_W56, -WHYDATE10YRHARD_TECH_W56, -WHYDATE10YREASYOE_M1_W56,-WHYDATE10YREASYOE_M2_W56,-WHYDATE10YREASYOE_M3_W56, -WHYDATE10YREASY_TECH_W56, -ONIMPACTPOSOE_M1_W56, -ONIMPACTPOSOE_M2_W56, 
-ONIMPACTPOSOE_M3_W56, -ONIMPACTNEGOE_M1_W56, -ONIMPACTNEGOE_M2_W56, 
-ONIMPACTNEGOE_M3_W56, -F_ACSWEB, -F_VOLSUM, -WEIGHT_W56_ATPONLY, -WEIGHT_W56)

#Get variable names from original dataset
var_names<-dput(names(raw_data))
#Convert variable names to single column with 183 rows
var_names <- cbind(var_names)

write_csv(raw_data, "raw_data")
```

```{r}
#Get questions from questionnaire corresponding to each variable
questions <- c("Marital Status", 
               "Current Committed Relationship Status", 
               "Have you ever been in a committed romantic relationship?", 
               "Are you currently casually dating anyone?", 
               "What they are seeking in their dating/romantic life", 
               "Whether \"Just like being single\" is a reason why not seeking relationship/dating", 
               "Whether \"Have more important priorities right now\" is a reason why not seeking relationship/dating", 
               "Whether \"Feel like I am too old to date\" is a reason why not seeking relationship/dating",
               "Whether \"Have health problems that make it difficult to date\" is a reason why not seeking relationship/dating",
               "Whether \"Haven’t had luck with dating or relationships in the past\" is a reason why not seeking relationship/dating",  
               "Whether \"Too busy\" is a reason why not seeking relationship/dating", 
               "Whether \"Feel like no one would be interested in dating me\" is a reason why not seeking relationship/dating", 
               "Whether \"Not ready to date after losing my spouse (if widowed) or ending a relationship\" is a reason why not seeking relationship/dating",
               "How long have you been in your current romantic relationship?", 
               "Overall, would you say that things in your relationship are going...",
               "Overall, would you say that things in your dating life are going...", 
               "Have you ever used an online dating site or dating app?",
               "Are you currently using an online dating site or dating app?", 
               "How did you first meet your spouse or partner?", 
               "Where online did you first meet your spouse or partner?", 
               "Compared to 10 years ago, for most people, do you think dating is...", 
               "Is giving a hug acceptable on a first date?",
               "Is kissing acceptable on a first date?", "Is having sex acceptable on a first date?", 
               "Is sex between unmarried adults who are in a committed relationship acceptable?", 
               "Is having an open relationship- that is, a committed relationship where both people agree that it is acceptable to date or have sex with other people acceptable?", 
               "Is casual sex between consenting adults who are not in a committed relationship acceptable?", 
               "Is two consenting adults exchanging sexually explicit images of themselves acceptable?", 
               "Is kissing someone on a date without asking permission first acceptable?", 
               "Have you ever searched for information online about someone you were romantically interested in?", 
               "Regardless of whether you would do it yourself, do you think it’s ever acceptable for someone to look through their significant other’s cellphone without their knowledge?", 
               "If you decided after a first date that you didn’t want to go out with that person again, what is the most likely way you would let them know?", 
               "Is it acceptable to break up with someone you're casually dating in person?", 
               "Is it acceptable to break up with someone you're casually dating through a phone call?", 
               "Is it acceptable to break up with someone you're casually dating through email?", 
               "Is it acceptable to break up with someone you're casually dating through a private message on a social media site?", 
               "Is it acceptable to break up with someone you're casually dating through a text message?", 
                "Is it acceptable to break up with someone you're in a committed relationship with in person?", 
               "Is it acceptable to break up with someone you're in a committed relationship with through a phone call?", 
               "Is it acceptable to break up with someone you're in a committed relationship with through email?", 
               "Is it acceptable to break up with someone you're in a committed relationship with through a private message on a social media site?", 
               "Is it acceptable to break up with someone you're in a committed relationship with through a text message?", 
               "Do you think the increased focus on sexual harassment and assault over the last few years has made it easier or harder for MEN to know how to interact with someone they’re on a date with?",
               "Do you think the increased focus on sexual harassment and assault over the last few years has made it easier or harder for WOMEN to know how to interact with someone they’re on a date with?",
               "Overall, what type of effect would you say online dating sites and dating apps have had on dating and relationships?",
               "Compared to relationships that begin in person, in general, do you think relationships where people first meet through an online dating site or dating app are…",
               "In general, how safe do you think online dating sites and dating apps are as a way to meet people?",
               "How common is people being harassed or bullied on online dating sites and dating apps?",
               "How common is people receiving sexually explicit messages or images they did not ask for on online dating sites and dating apps?", 
               "How common is people lying about themselves to appear more desirable on online dating sites and dating apps?",
               "How common are privacy violations, such as data breaches or identity theft on online dating sites and dating apps?", 
               "How common is people setting up fake accounts in order to scam others on online dating sites and dating apps?",
               "Would you ever consider being in a committed relationship with someone who is of a different religion than you?", 
               "Would you ever consider being in a committed relationship with someone who is of a different race or ethnicity than you?", 
               "Would you ever consider being in a committed relationship with someone who has a significant amount of debt?",
               "Would you ever consider being in a committed relationship with someone who is raising children from another relationship?", 
               "Would you ever consider being in a committed relationship with someone who lives far away from you?", 
               "Would you ever consider being in a committed relationship with someone who is a Republican?", 
               "Would you ever consider being in a committed relationship with someone who is a Democrat?",
               "Would you ever consider being in a committed relationship with someone who makes significantly more money than you?", 
               "Would you ever consider being in a committed relationship with someone who makes significantly less money than you?", 
               "Would you ever consider being in a committed relationship with someone who voted for Donald Trump?", 
               "Would you ever consider being in a committed relationship with someone who voted for Hillary Clinton?", 
               "Would you ever consider being in a committed relationship with someone who is 10 years older than you?", 
               "Would you ever consider being in a committed relationship with someone who is 10 years younger than you?", 
               "How much pressure, if any, do you feel from family members to be in a committed relationship?",
               "How much pressure, if any, do you feel from your friends to be in a committed relationship?",
               "How much pressure, if any, do you feel from society to be in a committed relationship?", 
               "In the past year, how easy or difficult has it been for you to find people to date?", 
               "It has been difficult for you to find people to date because... there is a limited number of people in my area for me to date", 
               "It has been difficult for you to find people to date because... it's hard for me to find someone who meets my expectations", 
               "It has been difficult for you to find people to date because... it's hard to find someone who's looking for the same type of relationship as me", 
               "It has been difficult for you to find people to date because... it's hard for me to approach people", 
               "It has been difficult for you to find people to date because... people aren't interested in dating me", 
               "It has been difficult for you to find people to date because... I'm too busy", 
               "Overall, would you say your OWN personal experiences with online dating sites or dating apps have been…",
               "In general in the past year, has using online dating sites or dating apps made you feel more confident or insecure?",
               "In general in the past year, has using online dating sites or dating apps made you feel more optimistic or pessimistic?",
               "In general in the past year, has using online dating sites or dating apps made you feel more hopeful or frustrated?",
               "Have you ever gone on a date with someone you met through an online dating site or dating app?", 
               "Have you ever been in a committed relationship or married someone you first met through an online dating site or dating app?",
               "Have you ever come across the online dating profile of someone you already know offline?",
               "How important is it to you that online profiles included hobbies and interests?",
               "How important is it to you that online profiles included political affiliation?", 
               "How important is it to you that online profiles included religious beliefs?", 
               "How important is it to you that online profiles included occupation?", 
               "How important is it to you that online profiles included racial or ethnic background?", 
               "How important is it to you that online profiles included height?", 
               "How important is it to you that online profiles included if they have children?", 
               "How important is it to you that online profiles included type of relationship they're looking for?", 
               "How important is it to you that online profiles included photos of themselves?",
               "How easy or difficult was it for you to find people on online dating sites or dating apps who you were physically attracted to?", 
               "How easy or difficult was it for you to find people on online dating sites or dating apps who shared your hobbies and interests?",
               
               "How easy or difficult was it for you to find people on online dating sites or dating apps who were looking for the same kind of relationship as you?",
               "How easy or difficult was it for you to find people on online dating sites or dating apps who seemed like someone you would want to meet in person?", 
               "How would you characterize the number of messages you have received on dating sites/apps?",
               "How would you characterize the number of messages you have received from people you were interested in on dating sites/apps?", 
               "How well, if at all, do you feel you understand why online dating sites or dating apps present certain people as potential matches for you?",
               "How concerned are you, if at all, about how much data online dating sites or dating apps collect about you?",
               "Do you ever use social media sites, like Facebook, Twitter, or Instagram?", 
               "How often, if ever, do you see people posting things about their romantic relationships on social media?", 
               "In general, do the posts you see on social media about other people’s romantic relationships make you feel better or worse about your own relationships?",
               "In general, do the posts you see on social media about other people’s romantic relationships make you feel better or worse about your own dating life?", 
               "Have you ever used social media to check up on someone that you used to date or be in a relationship with?",
               "Have you ever used social media to share or discuss things about your relationship or dating life?",
               "As far as you know, does your spouse or partner have a cellphone?",
               "As far as you know, does your spouse or partner use social media sites?",
               "As far as you know, does your spouse or partner play video games on a computer, game console or cellphone?",
               "How important, if at all, is social media to you personally when it comes to keeping up with what's going on your spouse's or partner's life",
               "How important, if at all, is social media to you personally when it comes to showing how much you care about your spouse or partner?",
               "Have you ever felt jealous or unsure about your relationship because of the way your current spouse or partner interacts with other people on social media?",
               "How often, if ever, do you feel as if your spouse or partner is distracted by their cellphone when you are trying to have a conversation with them?",
               "How often, if ever, are you bothered by the amount of time your spouse or partner spends on their cellphone?", 
               "How often, if ever, are you bothered by the amount of time your spouse or partner spends on social media sites?", 
               "How often, if ever, are you bothered by the amount of time your spouse or partner spends playing video games?",
               "Have you ever given your spouse or partner the password or passcode to your email account?", 
               "Have you ever given your spouse or partner the password or passcode to any of your social media accounts?", 
               "Have you ever given your spouse or partner the password or passcode to your cellphone?",
               "Have you ever looked through your current spouse's or partner's cellphone without their knowledge?", 
               "Have you ever heard of ghosting?",
               "Have you ever heard of breadcrumbing?", 
               "Have you ever heard of phubbing?", 
               "Have you ever heard of catfishing?", 
               "Have you ever heard of friends with benefits?", 
               "Have you ever had someone you’ve gone out with suddenly stop answering your phone calls or messages without explanation (sometimes called “ghosting”)?",
               "Has someone you were dating or on a date with ever pressured you for sex?", 
               "Has someone you were dating or on a date with ever touched you in a way that made you feel uncomfortable?", 
               "Has someone you were dating or on a date with ever sent you sexually explicit images that you didn't ask for?", 
               
               "As far as you know, has someone you were dating or been on a date with ever spread rumors about your sexual history?", 
               "As far as you know, has someone you were dating or been on a date with ever shared a sexually explicit image of you without your consent?", 
               "As far as you know, has someone you were dating or been on a date with ever publically shared your contact information or address without your permission?", 
               "Thinking about your own personal experiences, has someone ever called you an offensive name ON AN ONLINE DATING SITE OR DATING APP?",
               "Thinking about your own personal experiences, has someone ever threatened to physically harm you ON AN ONLINE DATING SITE OR DATING APP?",
               "Thinking about your own personal experiences, has someone ever sent you a sexually explicit message or image you didn’t ask for ON AN ONLINE DATING SITE OR DATING APP?",
              "Thinking about your own personal experiences, has someone ever continued to contact you after you said you were not interested ON AN ONLINE DATING SITE OR DATING APP?",
               "What sex is your spouse or partner?",
               "Sexual orientation", 
              "Type of Metro Area?", 
              "Type of Region?", 
              "User Self ID?",  
              "Age Category", 
              "Sex", 
              "Education",  
              "Education (dichotomized)", 
              "Race/Ethnicity", 
              "Nativity", 
              "Citizenship Status", 
              "Marital Status", 
              "Religion", 
              "Born", 
              "Attend", 
              "Political Party", 
              "Political Party 2", 
              "Political Party 3", 
              "Income", 
              "Income (dichotomized)", 
              "Reg", 
              "Reg_KP", 
              "Ideology")
```

```{r}            
#Convert questions to single col, 183 rows
questions <- cbind(questions)

#Combine variables and questions into df
lookup_questions <- data.frame(var_names, questions)

write_csv(lookup_questions, "lookup_table")
```


```{r}

# Scales in the order in which you want them to appear
first_scale <- c(NA,"Not currently looking for a relationship or dates", "Casual dates only", "Either a comitted romantic relationship or casual dates", "A committed romantic relationship only", "Refused")
second_scale <- c(NA, "Not a reason", "Minor reason", "Major reason")
third_scale <- c(NA, "Less than 1 year", "1 year to less than 3 years", "3 years to less than 5 years", "5 years to less than 10 years", "10 years to less than 20 years", "20 years or more", "Refused")
fourth_scale <- c(NA, "Not at all well", "Not too well", "Fairly well", "Very well", "Refused")
fifth_scale <- c(NA, "No, but I used one more than 5 years ago", "No, but I have used one within the past year", "Yes, I am currently using an online dating site or dating app", "Refused")
sixth_scale <- c(NA, "Harder today", "About the same", "Easier today", "Refused")
seventh_scale <- c(NA, "Never acceptable", "Rarely acceptable", "Sometimes acceptable", "Always acceptable", "Refused")
eighth_scale <- c(NA, "Not contact them, and not respond if they contacted you", "Not contact them, but would let them know if they contacted you", "Contact them and let them know", "Refused")
ninth_scale <- c(NA, "Has made it harder for men", "Hasn't made much difference", "Has made it easier for men", "Refused")
tenth_scale <- c(NA, "Has made it harder for women", "Hasn't made much difference", "Has made it easier for women", "Refused")
eleventh_scale <- c(NA, "Mostly negative effect", "Neither positive or negative effect", "Mostly positive effect", "Refused")
twelfth_scale <- c(NA, "Less successsful", "Just as successful", "More successful", "Refused")
thirteenth_scale <- c(NA, "Not at all safe", "Not too safe", "Somewhat safe", "Very safe", "Refused")
fourteenth_scale <- c(NA, "Not at all common", "Not too common", "Somewhat common", "Very common", "Refused")
fifteenth_scale <- c(NA, "Definitely would NOT consider", "Probably would NOT consider", "Probably would consider", "Definitely would consider", "Have already done this", "Refused")
sixteenth_scale <- c("No pressure at all", "Not too much pressure", "Some pressure", "A lot of pressure", "Refused")
seventeenth_scale <- c("Very difficult", "Somewhat difficult", "Somewhat easy", "Very easy", "Refused")
eighteenth_scale <- c("Very negative", "Somewhat negative", "Somewhat positive", "Very positive", "Refused")
nineteenth_scale <- c("Insecure", "Neither", "Confident", "Refused")
twentieth_scale <- c("Pessimistic", "Neither", "Optimistic", "Refused")
twenty_first_scale <- c("Frustrated", "Neither", "Hopeful", "Refused")
twenty_second_scale <- c("Not at all important", "Not too important", "Somewhat important", "Very important", "Refused")
twenty_third_scale <- c("Not enough messages", "Just the right amount", "Too many messages", "Refused")
twenty_fourth_scale <- c("Not enough messages from people you were interested in", "Just the right amount", "Too many messages from people you were interested in", "Refused")
twenty_fifth_scale <- c("Not well at all", "Not too well", "Somewhat well", "Very well", "Refused")
twenty_sixth_scale <- c("Very concerned", "Somewhat concerned", "Not too concerned", "Not at all concerned", "Refused")
twenty_seventh_scale <- c("Never", "Rarely", "Sometimes", "Often", "Refused")
twenty_eighth_scale <- c("Worse about your own relationship", "Doesn't make much difference", "Better about your own relationship", "Refused")
twenty_ninth_scale <- c("Worse about your own dating life", "Doesn't make much difference", "Better about your own dating life", "Refused")
thirtieth_scale <- c("H.S. graduate or less", "Some college", "College graduate+", "Don't know/Refused")
thirty_first_scale <- c("Less than high school", "High school graduate", "Some college, no degree", "Associate's degree", "College graduate/some post grad", "Postgraduate")
thirty_second_scale <- c("Less than $10,000", "$10,000 to less than $20,000", "$20,000 to less than $30,000", "$30,000 to less than $40,000", "$40,000 to less than $50,000", "$50,000 to less than $75,000", "$75,000 to less than $100,000", "$100,000 to less than $150,000", "$150,000 or more", "Refused")
thirty_third_scale <- c("Very conservative", "Conservative", "Moderate", "Liberal", "Very liberal", "Refused")

scales <- list(first_scale, second_scale, third_scale, fourth_scale, fifth_scale, sixth_scale, seventh_scale, eighth_scale, ninth_scale, tenth_scale, eleventh_scale, twelfth_scale, thirteenth_scale, fourteenth_scale, fifteenth_scale, sixteenth_scale, seventeenth_scale, eighteenth_scale, nineteenth_scale, twentieth_scale, twenty_first_scale, twenty_second_scale, twenty_third_scale, twenty_fourth_scale, twenty_fifth_scale, twenty_sixth_scale, twenty_seventh_scale, twenty_eighth_scale, twenty_ninth_scale, thirtieth_scale, thirty_first_scale, thirty_second_scale, thirty_third_scale)

  
  ## if the factor levels are the same as the ones in the thirty_first_scale, reorder the levels to match this convention


## with help from 
## https://statisticsglobe.com/loop-through-data-frame-columns-rows-in-r/ especially, and

## https://campus.datacamp.com/courses/intermediate-r/chapter-2-loops?ex=8
## https://stackoverflow.com/questions/34646076/r-check-if-all-values-of-one-column-match-uniquely-all-values-of-another-column
## https://hbctraining.github.io/Intro-to-R/lessons/05_introR-data-wrangling2.html
## http://www.cookbook-r.com/Manipulating_data/Changing_the_order_of_levels_of_a_factor/
## https://stackoverflow.com/questions/44084798/getting-the-nth-column-of-a-dataframe-using-a-for-loop
## https://stackoverflow.com/questions/56820739/looping-over-dataframes-in-r-to-change-column-and-row-names
## https://stat.ethz.ch/R-manual/R-devel/library/base/html/colnames.html
## https://rdrr.io/r/base/colnames.html
## https://stat.ethz.ch/R-manual/R-devel/library/base/html/sort.html

raw_data <- data.frame(a = as.factor(c("Sometimes","Never", "Sometimes", "Always", "Never")),
                        b = as.factor(c("Likely", "Very Likely", "Unlikely", "Very Unlikely", "Very Unlikely")),
                        c = as.factor(c("Likely", "Very Likely", "Unlikely", "Very Unlikely", "Very Unlikely")),
                        d = as.factor(c("Sometimes","Never", "Sometimes", "Always", "Never"))
)
# ---------------------------
# ...and a couple fake scales
# ---------------------------
first_scale <- c("Never", "Sometimes", "Always")
second_scale <- c("Very Unlikely", "Unlikely", "Likely", "Very Likely")
# ----------------------
# Put scales into a list
# ----------------------
scales = list(first_scale, second_scale)
# ---------------------
# FUN PART STARTS HERE!
# ---------------------
# Loop over each column name
for(col in names(raw_data)) {
  # Loop over each possible scale
  for(scale in scales){
    # Check to see if all the levels in the column are contained in the current scale (to deal w/ missing levels)
    if ( all(levels(raw_data[[col]]) %in% scale)) {
      # When we find the right scale, reorder the factor levels
      cat("Before reordering:", levels(raw_data[[col]]), "\n")
      raw_data[[col]] <- factor(raw_data[[col]], levels = scale)
      cat("After reordering:", levels(raw_data[[col]]), "\n\n")
    }
  }
}

```
















